version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: 'elasticsearch'
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    container_name: 'kibana'
    image: kibana:7.10.1
    ports:
      - '5601:5601'
  redis:
    container_name: 'redis'
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    ports:
      - '6379:6379'

    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
