version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.10.1
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    image: kibana:7.10.1
    ports:
      - '5601:5601'
  redis:
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    ports:
      - '6379:6379'

    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
